# Copyright 2018 The Bazel Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "com_grail_rules_r_tests")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "com_grail_rules_r",
    path = "..",
)

load("@com_grail_rules_r//R:dependencies.bzl", "r_register_toolchains", "r_rules_dependencies")

r_rules_dependencies()

r_register_toolchains()

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "59536e6ae64359b716ba9c46c39183403b01eabfbd57578e84398b4829ca499a",
    strip_prefix = "rules_docker-0.22.0",
    urls = [
        "https://github.com/bazelbuild/rules_docker/releases/download/v0.22.0/rules_docker-v0.22.0.tar.gz",
    ],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "r_base",
    digest = "sha256:7d5243aa3c5010a0978a30eba38089f140ce9efd509aafe2267d794be94ccf44",
    registry = "index.docker.io",
    repository = "rocker/r-ver",
    tag = "4.1.2",
)

load("@com_grail_rules_r//R:repositories.bzl", "r_repository_list")

r_repository_list(
    name = "r_repositories_bzl",
    build_file_overrides = "@com_grail_rules_r_tests//cran:build_file_overrides.csv",
    other_args = {
        "pkg_type": "both",
    },
    package_list = "@com_grail_rules_r_tests//cran:packages.csv",
    remote_repos = {
        # CRAN does not retain binary archives for macOS.
        "CRAN": "https://cran.microsoft.com/snapshot/2022-02-28",
    },
)

load("@r_repositories_bzl//:r_repositories.bzl", "r_repositories")

r_repositories()

load("@com_grail_rules_r//R:dependencies.bzl", "r_coverage_dependencies")

r_coverage_dependencies()

load("@r_coverage_deps_bzl//:r_repositories.bzl", coverage_deps = "r_repositories")

coverage_deps()

http_archive(
    name = "com_google_protobuf",
    sha256 = "3bd7828aa5af4b13b99c191e8b1e884ebfa9ad371b0ce264605d347f135d2568",
    strip_prefix = "protobuf-3.19.4",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v3.19.4.tar.gz",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

local_repository(
    name = "workspaceroot",
    path = "workspaceroot",
)

# Define custom toolchains to test if R toolchains work correctly.
# See BUILD for actual definition of the R toolchains.
http_archive(
    name = "com_grail_bazel_toolchain",
    sha256 = "148e871e785ae699e6adfbb07afea241ee668dbc0c530e72a47356885fce0cb7",
    strip_prefix = "bazel-toolchain-0.7",
    urls = [
        "https://github.com/grailbio/bazel-toolchain/archive/0.7.tar.gz",
    ],
)

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    cxx_builtin_include_directories = {
        "linux-x86_64": ["/usr/share/R/include"],
        "darwin-x86_64": ["/Library/Frameworks/R.framework/Headers"],
    },
    llvm_version = "13.0.0",
    stdlib = {
        "linux-x86_64": "stdc++",
    },
)
