# Copyright 2018 The Bazel Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "com_grail_rules_r_tests")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "com_grail_rules_r",
    path = "..",
)

load("@com_grail_rules_r//R:dependencies.bzl", "r_register_toolchains", "r_rules_dependencies")

r_rules_dependencies()

r_register_toolchains()

http_archive(
    name = "com_google_protobuf",
    sha256 = "f6600abeee3babfa18591961a0ff21e7db6a6d9ef82418a261ec4fee44ee6d44",
    strip_prefix = "protobuf-3.4.0",
    urls = ["https://github.com/google/protobuf/archive/v3.4.0.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "44a830571e44c5f3c81cba058573a4359dd78df57f069e253902db048f059f4f",
    strip_prefix = "rules_docker-17805d11cf07c4390b24a09f3476fb264b5f20ad",
    urls = [
        "https://github.com/bazelbuild/rules_docker/archive/17805d11cf07c4390b24a09f3476fb264b5f20ad.tar.gz",
    ],
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
    container_repositories = "repositories",
)

container_repositories()

container_pull(
    name = "r_base",
    registry = "index.docker.io",
    repository = "rocker/r-base",
    tag = "latest",
)

load("@com_grail_rules_r//R:repositories.bzl", "r_repository_list")

r_repository_list(
    name = "r_repositories_bzl",
    build_file_overrides = "@com_grail_rules_r_tests//cran:build_file_overrides.csv",
    package_list = "@com_grail_rules_r_tests//cran:packages.csv",
    remote_repos = {
        "CRAN": "https://cloud.r-project.org",
    },
)

load("@r_repositories_bzl//:r_repositories.bzl", "r_repositories")

r_repositories()

load("@com_grail_rules_r//R:dependencies.bzl", "r_coverage_dependencies")

r_coverage_dependencies()
