# Copyright 2018 The Bazel Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' Collect coverage data of R code, to be found in "covr_trace_*" RDS files,
#' each one generated by a covered R package upon process exit (or when
#' the R package's environment is garbage collected).
#'
#' @param cfg The configuration object.
#' @return A character vector of LCOV-formatted lines.
collect_r_coverage <- function(cfg) {
  # Read and merge tracing files, and convert to LCOV format.
  trace_files <- list.files(path = cfg$covr_trace_dir,
                            pattern = "^covr_trace_[^/]+$",
                            full.names = TRUE,
                            all.files = TRUE)
  log("covr trace files:\n  ",
      paste(collapse="\n  ", trace_files))
  coverage <- structure(merge_r_coverage(trace_files), class="coverage")

  return (to_lcov(coverage))
}

#' merge multiple coverage files together. Assumes the order of coverage lines
#' is the same in each object, this should always be the case if the objects are
#' from the same initial library.
#'
#' @param files RDS coverage files.
merge_r_coverage <- function(files) {
  nfiles <- length(files)
  if (nfiles == 0) {
    return()
  }

  x <- readRDS(files[1])
  x <- as.list(x)
  if (nfiles == 1) {
    return(x)
  }

  names <- names(x)
  for (i in 2:nfiles) {
    y <- readRDS(files[i])
    for (name in intersect(names, names(y))) {
      # This differs from the covr:::merge_coverage behavior:
      # covr is designed to cover only one package at a time.  Here,
      # we need to combin with 'max' to avoid duplicate hits.
      x[[name]]$value <- max(x[[name]]$value, y[[name]]$value)
    }
    for (name in setdiff(names(y), names)) {
      x[[name]] <- y[[name]]
    }
    names <- union(names, names(y))
    y <- NULL
  }

  x
}

#' Export coverage info to the
#' {LCOV format}[http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php].
#' Currently, only line coverage is supported.
#'
#' @param x the coverage object returned from [package_coverage()].
#' @export
#' @examples
#' \dontrun{
#' to_lcov(package_coverage())
#' }
to_lcov <- function(x) {
  coverages <- covr:::per_line(x)

  if (length(coverages) == 0) {
    warning("no coverage information in R")
  }

  res <- NULL
  for (filename in names(coverages)) {
    coverage <- coverages[[filename]]
    values <- coverage$coverage
    res <- c(
      res,
      paste0("SF:", sub(
        sprintf("(/[^/]+){%d}/", as.numeric(Sys.getenv("GCOV_PREFIX_STRIP"))),
        "",
        filename)))
    for (lineno in seq_along(values)) {
      hits <- values[lineno]
      if (!is.na(hits)) {
        res <- c(res, paste0("DA:", lineno, ",", hits))
      }
    }
    res <- c(res, "end_of_record")
  }

  return (res)
}