# Copyright 2018 The Bazel Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' Consolidate all the coverage data files to a single LCOV-formatted file.
#'
#' The LCOV-formatted file ends in '.dat' and is automatically picked up
#' by Bazel.
#'
#' @export
report <- function() {
  cfg <- environment_configuration()

  cover <- c(collect_r_coverage(cfg),
             collect_native_coverage(cfg))

  # Even if there is no coverage data, Bazel currently still requires
  # a .dat file to be written.  Moreover, `writeLines(NULL, ...)` is an error.
  if (length(cover) == 0) file.create(cfg$main_output_file)
  else writeLines(cover, con = cfg$main_output_file)

  log('Coverage data saved to ', cfg$main_output_file)
}

#' Gather configuration from environment variables.
environment_configuration <- function(env = Sys.getenv()) {
  must <- function (name) {
    ans <- env[[name]]
    if (is.null(ans) || ans == "") {
      stop("environment variable '", name, "' is mandatory")
    }
    ans
  }
  coverage_dir <- must("COVERAGE_DIR")
  list(
    # Directory with the gcda files (native code coverage).
    gcda_dir = must("GCOV_PREFIX"),
    # The coverage manifest generated by Bazel.  Each line is the
    # path to an instrumented file, relative to the execution root.
    coverage_manifest_file = must("COVERAGE_MANIFEST"),
    # Directory with the covr_trace_* files.
    covr_trace_dir = coverage_dir,
    # Directory where the gcno and gcda files are copied (gcov requires
    # those files to tag along).
    native_working_dir = file.path(coverage_dir, "gcno"),
    # Where to write the consolidated coverage data.
    main_output_file = file.path(coverage_dir, "R.dat"),
    # Runfiles directory (Bazel).
    runfiles_dir = must("RUNFILES"),
    # Execution root (Bazel).
    exec_root = must("EXEC_ROOT"),
    # Path to the gcov command-line utility.
    gcov_bin = must("COVERAGE_GCOV_PATH")
  )
}